### ISSUE TITLE
Underfull \hbox (badness 10000) in \makevctitle

### ISSUE THREAD

**Issue by stephanlachnit** [moderncv/moderncv#108]
Currently building our template (or any other document using moderncv) raises a warning: `Underfull \hbox (badness 10000) in paragraph at lines 93--93`. This happens in `\makecvtitle`. I have no idea where exactly that underfull hbox is supposed to be, but let's track this issue, as it might confuse users.

**Comment by rmolina** [comment]
I am using the casual style. At least for this style, the issue is in the `\makecvhead ` command. Looking at its definition on the `moderncvheadii.sty` file, I can see things like `\\[2.5em]`. Changing them to `\vspace{2.5em}` solves the issue for me.

**Comment by Thrashophil** [comment]
The same in the classic style. Adding `\quote{}` to the header removes the bad box, but that's not a good coding style, especially for people who don't want to use a quote.

**Comment by tianyizheng02** [comment]
After poking around the header package files for a bit, I believe that the `Underfull \hbox (badness 10000)` warning stems from an issue with the vertical spacing between the quote and the rest of the header. The template currently uses the classic style, and on [line 140](https://github.com/moderncv/moderncv/blob/d5ffdb5a8022385e282300e8b9fba2e9c37e2aba/moderncvheadi.sty#L140) of `moderncvheadi.sty` that vertical spacing is set using a `\\[2.5em]`:
```latex
\if@right%
  \usebox{\makecvheadpicturebox}%
  \rlap{\usebox{\makecvheaddetailsbox}}% \llap is used to suppress the width of the box, allowing overlap if the value of makecvheadnamewidth is forced
  \hfill%
  \usebox{\makecvheadnamebox}\fi%
\\[2.5em]%
% optional quote
\ifthenelse{\isundefined{\@quote}}%
  {}%
  {{\centering\begin{minipage}{\quotewidth}\centering\quotestyle{\@quote}\end{minipage}\\[2.5em]}}%
\par}% to avoid weird spacing bug at the first section if no blank line is left after \makecvhead
```
The warning appears if and only if there is no quote. I tried changing just that `\\[2.5em]` to `\vspace{2.5em}`. This appears to fix the warning when there is no quote _but breaks the quote formatting when there is one._

So I had the package choose between one or the other based on whether there is a quote:
```latex
\if@right%
  \usebox{\makecvheadpicturebox}%
  \rlap{\usebox{\makecvheaddetailsbox}}% \llap is used to suppress the width of the box, allowing overlap if the value of makecvheadnamewidth is forced
  \hfill%
  \usebox{\makecvheadnamebox}\fi%
% optional quote
\ifthenelse{\isundefined{\@quote}}%
  {\vspace{2.5em}}%
  {%
    \\[2.5em]%
    {\centering\begin{minipage}{\quotewidth}\centering\quotestyle{\@quote}\end{minipage}\\[2.5em]}}%
\par}% to avoid weird spacing bug at the first section if no blank line is left after \makecvhead
```
This fixes the warning in both cases without breaking the quote formatting, but I feel like this is kind of a hacky solution. What do you think, @stephanlachnit? If this solution seems OK to you, then I can make similar changes for the other header package files and open a PR.

**Comment by mefuller** [comment]
Despite calling it a "hacky solution", it's still a solution and I'd welcome a PR to address this bug
