### ISSUE TITLE
Add Discord to the social links

### ISSUE THREAD

**Issue by Coy-Allen** [moderncv/moderncv#111]
Would it be possible to add discord to the list of social links?

**Comment by mefuller** [comment]
@Coy-Allen I have templated this in pull request #112  - would you please take a look and also provide the format for Discord handles and links to them?

**Comment by Coy-Allen** [comment]
@mefuller Normally you use the app to and their handles. It includes their username, hash, and a 4 number code for example "coy1#1001".
There is no straight forward way to link to someone's account via HTTP. While it is possible it uses a separate hidden internal account ID. The pull request seems fine but I would just not have it link to anything at all if possible.

**Comment by mefuller** [comment]
Closed by #112
