### ISSUE TITLE
`\bfseries` and `\textbf{}` are not working properly

### ISSUE THREAD

**Issue by RakeshJarupula** [moderncv/moderncv#118]
I was compiling new modercv template on Overleaf platform...I am not getting bold text as shown in the preview images.

Template: https://www.overleaf.com/latex/examples/resume-template-for-software-engineer/fvsqzcybnwdn 
![7344](https://user-images.githubusercontent.com/53005533/160279296-b985eed3-aab6-4625-abdb-1a7873c81702.jpeg)

After compiling: 
![latex](https://user-images.githubusercontent.com/53005533/160279272-e6da5315-980e-4b5a-96e6-bd202674a508.JPG)

**Comment by ShadowMitia** [comment]
I've applied the solution from https://github.com/moderncv/moderncv/issues/102 and it seems to fix your issue.
You can also try and use a more recent verison of moderncv, the one on overleaf is recent but isn't the latest one.

**Comment by RakeshJarupula** [comment]
Thank you @ShadowMitia :)

**Comment by khatchad** [comment]
I had the same issue. For me, the culprit was `\usepackage{CJK}`.
