### ISSUE TITLE
Social media link: GitHub links incomplete

### ISSUE THREAD

**Issue by sdicke** [moderncv/moderncv#120]
Example:` \social[github][www.github.com]{sdicke}` will generate the link [https://github.com/](https://github.com/).

Obviously the argument from the curly brackets is not included in the generated link.

**Comment by ShadowMitia** [comment]
You don't need the second square brackets: this works fine `\social[github]{sdicke}`

**Comment by sdicke** [comment]
Thanks. Without the second brackets the correct link is generated. Then I took the mistake from the tutorial I used.
