### ISSUE TITLE
LaTeX Error: Unicode character ​ (U+200B) not set up for use with LaTeX.

### ISSUE THREAD

**Issue by zpapadakis** [moderncv/moderncv#126]
I am trying to compile a vitae modernCV with RMarkdown and i am getting the following error
I was unable to find any missing LaTeX packages from the error log CV.log.
! LaTeX Error: Unicode character ​ (U+200B)
               not set up for use with LaTeX.
Amy help?
Thanks

**Comment by mefuller** [comment]
U+200B is a zero-width space and it is not supported in PDFLaTeX (see https://tex.stackexchange.com/questions/352623/unicode-char-u200b) - you need to remove it or use a different compiler, XeLaTeX or LuaLaTeX should work (although I am not so familiar with the latter).

**Comment by zpapadakis** [comment]
The thing is that everything was working couple weeks ago...how to identify th ezero width error so I manually delete it?

**Comment by mefuller** [comment]
For moderncv, I would recommend using XeLaTeX as the compiler over pdfLaTeX.

That should avoid having an error thrown for the Unicode character and also allow use of the full set of symbols.

I'm closing this issue as it is unrelated to moderncv.
