### ISSUE TITLE
Using 'banking' style, the full resume title is printed above the cover letter

### ISSUE THREAD

**Issue by podono** [moderncv/moderncv#127]
![Screenshot 2022-08-15 031157](https://user-images.githubusercontent.com/6591736/184562455-051f1a2a-9306-45f5-baa4-fde7b4c3366b.png)

To remove the title, open 'moderncvheadiii.sty' (banking head style) and comment out the lines:
  % sender block
  \makehead%
  \par%

Given that the banking style is the only one to print the full title above the cover letter, this might be unintended. Or perhaps the sender block should be copied from the 'classic' or 'fancy' styles.

Cheers!

**Comment by stephanlachnit** [comment]
Good spot! Definitely something that should be fixed

**Comment by mefuller** [comment]
[template.pdf](https://github.com/moderncv/moderncv/files/10491158/template.pdf)
