### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by mefuller** [moderncv/moderncv#129]
Add issue templates for reporting bugs to (hopefully) improve the quality of reports and minimize iterations required to get an actionable report from users

**Comment by mefuller** [comment]
I don't seem to have appropriate permission levels to implement this myself (see instructions at https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

@stephanlachnit can you elevate my permissions to edit repo settings?
I want to add a very basic issue template, like the following:

```
## Expected Behavior


## Actual Behavior


## Minimum Working Example to Reproduce the Problem


## Specifications

  - moderncv version and source:
  - LaTeX compiler (pdfLaTeX, XeLaTeX, etc.) and version:
  - Platform (operating system, LaTeX editor, etc.):
```

**Comment by stephanlachnit** [comment]
Interesting, can you try again now?

**Comment by mefuller** [comment]
Yes - I see the 'settings' menu now and I added a bug report template
Thanks
