### ISSUE TITLE
CTAN update

### ISSUE THREAD

**Issue by Peque** [moderncv/moderncv#13]
It would be great to push a new updated version to the CTAN. Hopefully with the StackOverflow `\social` command included! :innocent: 

Also the repository link at CTAN still points to Launchpad.

**Comment by stephanlachnit** [comment]
Sorry for being not so active - I will try to get a release done in October and contact CTAN.

**Comment by stephanlachnit** [comment]
Uploaded 2.1.0 to CTAN, but ofc it needs to be accepted first.

**Comment by D4nte** [comment]
> Uploaded 2.1.0 to CTAN, but ofc it needs to be accepted first.

Can we help with this process?

**Comment by stephanlachnit** [comment]
> Can we help with this process?

Yes, indeed. Sorry for not giving updates here. I got an answer some time ago:

> Before we install this update on CTAN, please make the following changes:
>
> (1) Please continue the CHANGELOG, which at present stops in
>     2015,  to the current version and date,  so that it gives
>     "the whole truth".  Please mention also the change of
>    maintainer(s) and the reason for this.
>
> (2) Version and date should also be changed in line 13 of
>     moderncv.cls,
>
> Question:  What is the difference between "moderncv_userguide.pdf"
> and "moderncv_userguide.v2.pdf"?  —  A _single_ user manual would
> be less confusing.
>
> Finally:  Please omit the .gitignore file and the .github/
> directory from future uploads.  Thanks!
>
> Please make these little changes and re-upload.

I didn't really have the motivation to make the changes (low on my prio list), but if you want to help, here are my suggestions:
- Figure out the difference between the two user guides and delete one of them
- Write a small script to create a tar.gz with only the .github and .gitignore stuff
- Update the changelog for version v2.1.0
- Update the date and version in `moderncv.cls` (go with the current date, I will force-push the tag anyway)

These are pretty simple and if they are done I will take the time to do the chore and upload it again.

**Comment by stephanlachnit** [comment]
Just uploaded v2.1.0 :)

**Comment by stephanlachnit** [comment]
New version is up: https://www.ctan.org/pkg/moderncv
