### ISSUE TITLE
Option to align header elements to the top

### ISSUE THREAD

**Issue by flg** [moderncv/moderncv#130]
It would be nice to have an option to align elements of the header (Name+title, details, photo) on their top rather than at their bottom.

A solution is provided in this stackexchange entry: https://tex.stackexchange.com/questions/82167/align-names-data-and-picture-in-cv
It works (at the exception of a few glitches).

**Comment by mefuller** [comment]
Hi @flg - thanks for commenting.
Would you be interested in developing and submitting a PR with these changes?

**Comment by flg** [comment]
Hi @mefuller 
I finally found some time to look into it and just submitted a pull request. Comments are welcome.
