### ISSUE TITLE
Put color definitions in a standalone file

### ISSUE THREAD

**Issue by wenh06** [moderncv/moderncv#136]
**Is your feature request related to a problem? Please describe.**

We can put all color definitions in one file, and (re)use them everywhere using commands `\input` and `\colorlet`.

**Describe the solution you'd like**

For example, my file structure is

```
├── commons
│   ├── bib-settings.tex
│   ├── colors.tex
│   ├── html-color-codes.tex
│   ├── newcommands.tex
│   └── socials.tex
├── ...
```

I put all my color definitions in `commons\colors.tex` as follows

```
%---------------------------------------------------------------------------------------
% user-defined colors

\definecolor{tsinghua}{rgb}{.434, .09, .531}
\definecolor{tsinghua-1}{HTML}{791CB5}
\definecolor{tsinghua-2}{HTML}{4B0C77}

%---------------------------------------------------------------------------------------
% colors for social icons

\definecolor{weixin}{rgb}{.184, .533, .098}
\definecolor{linkedin}{HTML}{0a66c2}
\definecolor{orcid}{HTML}{a6ce39}
\definecolor{twitter}{RGB}{29, 155, 240}
\definecolor{facebook}{HTML}{1b74e4}


%---------------------------------------------------------------------------------------
% built-in colors

\definecolor{black}{RGB}{0, 0, 0}
\definecolor{red}{rgb}{0.95, 0.20, 0.20}
\definecolor{darkgrey}{rgb}{0.45, 0.45, 0.45}
\definecolor{orange}{rgb}{0.95, 0.55, 0.15}
\definecolor{burgundy}{rgb}{0.596078, 0, 0}% 139/255 (0.545098) or 152/255 (0.596078)
\definecolor{purple}{rgb}{0.50, 0.33, 0.80}
\definecolor{lightblue}{rgb}{0.22, 0.45, 0.70}
\definecolor{green}{rgb}{0.35, 0.70, 0.30}
```

In `moderncvcolorred.sty`, one can write

```
\input{commons/colors}

\colorlet{color0}{black}% black
\colorlet{color1}{red}% red
\colorlet{color2}{darkgrey}% dark grey
```

instead of defining the black and dark grey colors again and again.

Also in files `moderncviconsawesome.sty` and `moderncviconsacademic.sty`, we can use `\input{commons/colors}` (both) and `\renewcommand*{\orcidsocialsymbol}        {{\color{orcid}\small\faOrcid}~}`, `\renewcommand*{\orcidsocialsymbol}        {{\color{orcid}\small\aiOrcid}~}` (respectively) to get colored icons.

**Describe alternatives you've considered**

NA

**Additional context**

NA

**Comment by mefuller** [comment]
Please do submit a pull request for review

**Comment by mefuller** [comment]
Closed by #137

**Comment by davidcarlisle** [comment]
`colors.tex` is a bad name for a file in the global default input tree, (it is not distributed in texlive and currently leads to errors after an update

https://tex.stackexchange.com/questions/722345/file-commons-colors-tex-not-found

could the file be renamed to `modernccv-colors.tex` or something?

**Comment by koppor** [comment]
@davidcarlisle There was an issue filed at https://github.com/moderncv/moderncv/issues/194 - which is fixed at https://github.com/moderncv/moderncv/issues/195

**Comment by davidcarlisle** [comment]
@koppor  so there was, thanks for the fix, and sorry for the noise.
