### ISSUE TITLE
Show promotions in the same company.  

### ISSUE THREAD

**Issue by steve-the-bayesian** [moderncv/moderncv#138]
The cv-entry model goes date-place, date-place.  If you've been at a place (company, university) for a long time you might have been promoted.  In that case there's a third variable "role".   Something like "hooli 2008 - 2012 engineer, 2012-2018 engineering manager, 2018 - present director".  

I don't see a method of organizing job history this way.

**Comment by ravbag** [comment]
This is  already covered, check moderncvbodyiii.sty
% skip the company name and location line if both are empty, allowing one to show multiple roles within the same company without repeating it

So basically all you need to do is leave the company name and location empty and the position will be displayed as multiple roles. This is especially useful if you use the "oldstyle" option
