### ISSUE TITLE
Undefined control sequence \if@aftersection with \moderncvhead{5}

### ISSUE THREAD

**Issue by pietvo** [moderncv/moderncv#139]
**Describe the bug**

If you use `\moderncvhead{5}` in your document, you get a LaTeX error message

**Expected Behavior**

Compile the document without error

**Actual Behavior**

An error message is given and the document doesn't compile.

```
./cvexample.tex:13: Undefined control sequence.
\\@makecvtitle ...width {1.2\p@ }\if@aftersection 
                                                  \else \vspace *{-\arrayrul...l.13     \makecvtitle
```                     

**Minimum Working Example to Reproduce the Problem**

```
\documentclass{moderncv}

\moderncvtheme[blue]{classic}
\moderncvhead{5}

\firstname{Firstname}
\familyname{Lastname}
\title{Resume}

\photo{example-image}  

\begin{document}
    \makecvtitle
\end{document}
```

**Specifications**
  - moderncv version and source: moderncv 2022-02-21 v2.3.1 from texlive 2022
  - LaTeX compiler (pdfLaTeX, XeLaTeX, etc.) and version: pdfLaTeX Version 3.141592653-2.6-1.40.24 (TeX Live 2022)  (preloaded format=pdflatex 2022.10.14)  15 OCT 2022 14:24
  - Platform (operating system, LaTeX editor, etc.): MacOS Catalina 10.15.7

**Additional context**

The `\if@aftersection` is defined in `moderncvbodyv.sty` and used in `moderncvheadv.sty`, so the logical solution would be to also specify `\moderncvbody{5}`, although I didn't see a requirement to use these together. However, when you do this, you get another error:

```
LaTeX Error: Option clash for package moderncvskillmatrix.
```

**Comment by mefuller** [comment]
The #5 options set are used in the fancy style CV.
Each of the CV style options calls and sets the head, foot, and body options that are appropriate.
It is not intended (at least not by me) that they be "mixed and matched"
