### ISSUE TITLE
File `commons/colors.tex` not found, Emergency stop, failed to compile.

### ISSUE THREAD

**Issue by amalgame21** [moderncv/moderncv#141]
Sorry I am very very new to LaTeX (started to learn it a week ago), I may only did something wrong.

**Describe the bug**

Inside an empty folder, put the `Template.tex` in it, and compile the `.tex` file there.

Error message: 
`Template.tex || File "commons/colors.txt" not found.` 
`/usr/share/texmf/tex/latex/moderncv/moderncviconsawesome.sty |25 error| Emergency stop.`

**Expected Behavior**
Compile properly

**Actual Behavior**
Failed to compile, require to download `commons/colors.txt` into the folder to compile properly. It should be optional (in my opinion).

**Minimum Working Example to Reproduce the Problem**

1. Install moderncv witn `paru -S texlive-moderncv-git ttf-font-awesome-5 stf-font-awesome-5` since arch linux do not have the latest version of `moderncv` in the `texlive-latexextra` package. The AUR `ttf-font-awesome-5 stf-font-awesome-5` packages are necessary because arch linux pumped the awesome font version to 6.

2. Inside an empty folder, put the `Template.tex` (from this repo) in it, and compile the `.tex` file there.

3.  Error message as described above.

I guess  #137 cause this.

I originally thought the `commons/colors.tex` file is optional for people want to redefine the colors. Now it seems we must include it in every directories using `moderncv`. I do not know whether it is by design or not.

**Specifications**
  - moderncv version and source: texlive-moderncv-git
  - LaTeX compiler (pdfLaTeX, XeLaTeX, etc.) and version: latexmk, xelatex engine
  - Platform (operating system, LaTeX editor, etc.): Endeavouros, nvim with vimtex plugin

**Additional context**

BTW, the `moderncv` is a very good tool! 
Thank you for your work! I should have discovered it sooner!

**Comment by mefuller** [comment]
The current situation is by design as color definitions were previously duplicated in the various styles.
The colors files, like the style and class files, are necessary to support the compilation of template.TeX.
It seems that you have a "franken" setup with some mixing and matching which should be a non-issue when installing a versioned release or using the complete current master.
