### ISSUE TITLE
Multiple Author add in publication.bib

### ISSUE THREAD

**Issue by nasim-aust** [moderncv/moderncv#142]
**Is your feature request related to a problem? Please describe.**
I wanted to my publications in the publication.bib file. But if I add multiple author in the author section it doesn't work properly and also doesn't maintain the order or comma.

**Describe the solution you'd like**
The author name should be a proper way like as any publication reference.

**Describe alternatives you've considered**
Is there any way how can I add in the current file?

![image](https://user-images.githubusercontent.com/16854243/202759309-d63dc7ba-c16e-41f1-a3ea-60456e55498e.png)

**Comment by nasim-aust** [comment]
@mefuller Would you please check it?

**Comment by mefuller** [comment]
@nasim-aust would you please post your source code and not a screenshot?

Alternatively, see my files at 
https://codeberg.org/fuller/fuller-moderncv/src/branch/main/FullerMarkE_CV-academic.tex
and
https://codeberg.org/fuller/fuller-moderncv/src/branch/main/ownpubspres-CV.bib
for a working example

Feel free to contact me directly or ask for additional help in the [moderncv matrix channel](https://matrix.to/#/#moderncv:matrix.org)

Closing as this is not a bug
