### ISSUE TITLE
\social[mastodon]{stuff} and \social[codeberg]{stuff} produce nothing

### ISSUE THREAD

**Issue by pagiraud** [moderncv/moderncv#143]
**Describe the bug**
```
\social[github]{stuff} %works (also true for orcid, linkedin, etc.)
\social[mastodon]{stuff} %doesn’t work
\social[codeberg]{stuff} %neither
```

**Expected Behavior**
They produce something.

**Actual Behavior**
They produce nothing (not even in the log or aux files).

**Minimum Working Example to Reproduce the Problem**

```
\documentclass{moderncv}
\moderncvstyle{casual}
\firstname{John}
\familyname{Smith}
\social[github]{foo}
\social[mastodon]{bar}
\begin{document}
	\makecvtitle
\end{document}
```

**Specifications**
  - moderncv version and source: 2.3.1 from Texlive 2022.20220722-2 (Ubuntu 22.10 version)
  - LaTeX compiler (pdfLaTeX, XeLaTeX, etc.) and version: Lualatex (default Ubuntu 22.10 version)
  - Platform (operating system, LaTeX editor, etc.): Ubuntu 22.10 with Texstudio 4.4.1 (.deb from official website).

Thanks for this great class.

**Comment by pagiraud** [comment]
Ok, I think I got it. The merge #107 didn’t make it to 2.3.1 (I didn’t find any occurence of mastodon or codeberg in it) but, for some reason, Texstudio thinks it did… when I type \social[mas I have the autocomplete for mastodon, same for codeberg.

So, maybe, an enhancement would be some kind of warning in log when one has triggered a \social[whatever] that doesn’t exist.

I can close this issue or change its title, whatever seems better for you.

**Comment by mefuller** [comment]
{I'm on a train, so hard to review right now}
If you have a moment, check your local template.tex in your installation and/or the same in the 2.3.1 release on GitHub.
If mastodon or codeberg is present,  then this is something that needs to be cleared up.
Otherwise it's unclear to me why your editor suggests them.
You can, of course, grab the current master to enjoy those features.

**Comment by pagiraud** [comment]
Well, I had a bit of a hard to find the origine of the problem. There is no problem with the moderncv package distributed with TexLive. I wanted to look at the cwls provided by Texstudio for autocompletion, but it turns out they are hardcoded in the bin file, so my searches on my harddrive gave me nothing…

So I went to their repo and… there it is! mastodon and codeberg are in the [class-moderncv.cwl](https://github.com/texstudio-org/texstudio/pull/2130/commits/62f6184c7ce5b2d086d9a5931ef294b5784b96f6) since 2022/02/23 and thus included in all then released versions of Texstudio. It’s a problem on their side: do you think I should report it?

**Comment by j-lakeman** [comment]
Hey guys, just found this issue as I also ran into it. I'm using `tectonic` to compile which pulls the latest individual packages needed.
Codeberg entry is still not working for me independently of TeXstudio.
Any hints on how to resolve this?
