### ISSUE TITLE
no way to force http URL for homepage

### ISSUE THREAD

**Issue by darthoctopus** [moderncv/moderncv#147]
**Describe the bug**

#7 forces all hyperlinks to be https by default. However, unlike social media, not all web hosts necessarily support https (particularly academic websites self-hosted by individual departments)

**Expected Behavior**

Some way to force `\homepage` to use http should exist.

**Actual Behavior**

No such flag exists

**Specifications**

Not relevant

**Comment by mefuller** [comment]
@darthoctopus I can certainly implement this change (once I find a little time), but I would also be happy to review and merge a pull request if you are interested in writing it

**Comment by ingemarberg** [comment]
@mefuller I've made a pull request which should fix this. Even though I've used LaTeX to typeset documents before, this was new to me. Would you be able to review #154? If so, please let me know if there's any better way to solve this.

**Comment by mefuller** [comment]
Closed by #154
