### ISSUE TITLE
Add your personal signature to cover letter

### ISSUE THREAD

**Issue by LLdaniel** [moderncv/moderncv#156]
**Is your feature request related to a problem? Please describe.** 
Feature suggestion, _not_ a bug: 
Maybe this is a personal thing, but I like to write my signature in the cover letter closing. Therefore I tried to integrate it with a `\includegraphics` of `\usepackage{graphicx}` in my personal modification of moderncv. 
Could look like this:
![image](https://user-images.githubusercontent.com/41345639/228670244-db800082-9c90-4373-b2f2-30340bcd24ac.png)

**Describe the solution you'd like**
I would be glad if we could discuss the signature feature in the cover letter and if this would be an idea for upstream. 

**Describe alternatives you've considered**
Alternatively I also can leave it in my fork and we do not need to push it upstream - it is just a suggestion.

**Additional context**
I already tried to create a minimal viable solution in my moderncv fork. 
Feel free to have a look at it: https://github.com/LLdaniel/moderncv_mod/tree/feature/signature-coverletter.

I am currently working on my branch to make the signature optional. Maybe I should create a pull request after that change?

**Comment by mefuller** [comment]
An option to load a signature from a image should be fine. I would not consider a PR before that change is implemented.

My reasoning (story time):
The traditional approach (in the days of yore), which I would say is implicit in the current letter, is to print (or type!) the letter and then manually sign (N.B. blue ink in the post-fax machine, pre-color scanner and printer world) the finished product before mailing it off.

With the advent of electronic submission, my general impression has been that the typed format has remained, specifically the space to add a manual signature to a hard copy is preserved.
Optionally overriding that space with a graphic seems like a reasonable option.

**Comment by LLdaniel** [comment]
That sounds good I also like your story and have to admit: The prettiest solution is a handwritten signature in blue ink. 👍

But for electronic submissions we maybe could use the next best solution and offer the signature as a picture. 

I would like to work on that idea and will present a possible solution soon! (Currently it is a good time for me to do so, because I am updating my cv anyway 😅).

**Comment by tianyizheng02** [comment]
Fixed by #157, so probably good to close

**Comment by LLdaniel** [comment]
Yes, this issue has no pending to dos left after the merge. Therefore I close it.
