### ISSUE TITLE
Template Build Fails

### ISSUE THREAD

**Issue by icedwater** [moderncv/moderncv#166]
**Describe the bug**
Build failed with pdflatex and latexmk
```
(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty)
! Undefined control sequence.
l.125   \IfPDFManagementActiveTF
                                {}{\RequirePackage[T1]{fontenc}}
?
```

**Expected Behavior**
Example PDF is shown when `latexmk -pdf template.tex` is run, or `pdflatex template.tex`.

**Actual Behavior**
Compiler fails with similar message to above.

**Minimum Working Example to Reproduce the Problem**

    git clone git@github.com:moderncv/moderncv
    cd moderncv
    latexmk -pdf template.tex
    # pdflatex template.tex

**Specifications**
  - moderncv version and source: 2.3.1
  - LaTeX compiler (pdfLaTeX, XeLaTeX, etc.) and version: pdflatex 3.1415926-2.6-1.40-20; latexmk 4.67
  - Platform (operating system, LaTeX editor, etc.): Ubuntu 20.04

**Comment by mefuller** [comment]
I'm unable to reproduce this issue running `latexmk -pdf template.tex` on mac; our CI runs on Ubuntu latest and is also not showing any errors.
Please check that you have the fontenc package installed

Also, are you using v2.3.1 from the distro repo or running master? The report is inconsistent

**Comment by icedwater** [comment]
Sorry about the wasted effort. I'll try to recreate the bug - I've since
built on another machine without issues.

I pulled the latest from the repository on that day but couldn't find a
matching version number for the report, so I either dug around in the
changelog to see what the most recent version number was, or took the
closest number I could find in the GitHub UI drop-down list of tags.

If I find a similar issue again, I'll reopen this ticket with
clarifications.

**Comment by slabstone** [comment]
I'm getting the same error, tried to build with `texlive-base`, `texlive`, `texlive-full` and even installed `texlive-full` with `--install-suggests`, still no luck. Building in Docker image `thomasweise/docker-texlive-full:latest` (as in GitHub workflow) works though, and this image installs _a lot_ of packages, so I think the problem is that some packages are missing/outdated on my system.
