### ISSUE TITLE
Consider creating a new tag (last tag is more than a year old)

### ISSUE THREAD

**Issue by klartext** [moderncv/moderncv#168]
Hello,

TeXLive currently offers the moderncv class from 2022-02-21 (v. 2.3.1).
Looking at CTAN, same result: https://ctan.org/pkg/moderncv?lang=en

The reason: looking for the available tags here in the repo shows me, there is no newer tag avaialable.

So, to have a more recent class available via TeXLive & Co., please consider adding a new tag.

**Comment by tianyizheng02** [comment]
There have been plans for version 2.4.0 for well over a year. See the [milestones](https://github.com/moderncv/moderncv/milestones) section of this repo for more details on current progress made toward 2.4.0.

**Comment by stephanlachnit** [comment]
Feel free to open a PR with a changelog - I can create a tag and upload the changes to CTAN.

**Comment by tianyizheng02** [comment]
> Feel free to open a PR with a changelog - I can create a tag and upload the changes to CTAN.

@stephanlachnit I think there's already been work done on a changelog in #58, should we try to get that PR completed and merged instead?

**Comment by mefuller** [comment]
@tianyizheng02 please - getting the userguide and other docs up to date is a big open item
I would certainly appreciate any help there

**Comment by stephanlachnit** [comment]
> > Feel free to open a PR with a changelog - I can create a tag and upload the changes to CTAN.
> 
> @stephanlachnit I think there's already been work done on a changelog in #58, should we try to get that PR completed and merged instead?

The Userguide PR have some nice changes but they are a bit older and need some heavy rebasing. Feel free to take a look at it, otherwise a small PR with just the changelog of the things merged until now is fine with me as well.

**Comment by tianyizheng02** [comment]
@mefuller @stephanlachnit I just opened a PR (#169) that rebases #58. I'd really appreciate it if you could review it when you get the chance. If there are additions to the changelog made in #58 that aren't in the current changelog, I can add them to my PR and bring the changelog up-to-date as well.
