### ISSUE TITLE
How to add a \cvtripleitem command

### ISSUE THREAD

**Issue by djrmarques** [moderncv/moderncv#174]
**Describe the solution you'd like**
There is currently a command called `\cvdoubleitem` that adds two items side by side. I would like to create a `\cvtripleitem` that does the same but with three columns side by side.

**Describe alternatives you've considered**
```latex
% makes a resume line 2 headers and their corresponding text
% usage: \cvdoubleitem[spacing]{header1}{text1}{header2}{text2}
\newcommand*{\cvdoubleitem}[5][.25em]{}
```

I have looked into the class file and found the the code above. I suppose I could add a new command, but I don't understand how to make it add three columns side by side. 

**Additional context**
I hope this is not a stupid question, I am not very proficient with latex :)

**Comment by LLdaniel** [comment]
I just tinkered a bit and maybe I can help you out. For my starting point I modified `moderncvbodyi.sty` for the `classic` style.
Basically I went your described path and created a `\cvtripleitem` similar to the `\cvdoubleitem`.

Does it help when I add my `git diff` compared to the current `master`?
It looks like this:
```
diff --git a/moderncv.cls b/moderncv.cls
index 271ca6c..5825612 100644
--- a/moderncv.cls
+++ b/moderncv.cls
@@ -552,6 +552,10 @@
 % usage: \cvdoubleitem[spacing]{header1}{text1}{header2}{text2}
 \newcommand*{\cvdoubleitem}[5][.25em]{}
 
+% makes a resume line 3 headers and their corresponding text
+% usage: \cvtripleitem[spacing]{header1}{text1}{header2}{text2}{header3}{text3}
+\newcommand*{\cvtripleitem}[7][.1em]{}
+
 % makes a resume line with a list item
 % usage: \cvlistitem[label]{item}
 \newcommand*{\cvlistitem}[2][\listitemsymbol]{}
diff --git a/moderncvbodyi.sty b/moderncvbodyi.sty
index 5099ad2..30ad56a 100644
--- a/moderncvbodyi.sty
+++ b/moderncvbodyi.sty
@@ -44,6 +44,8 @@
 \@initializelength{\maincolumnwidth}
 %   used by \cvdoubleitem
 \@initializelength{\doubleitemcolumnwidth}
+%   used by \cvtripleitem
+\@initializelength{\tripleitemcolumnwidth}
 %   used by \cvlistitem
 \@initializelength{\listitemsymbolwidth}          \settowidth{\listitemsymbolwidth}{\listitemsymbol}
 \@initializelength{\listitemcolumnwidth}
@@ -59,6 +61,8 @@
   \setlength{\listitemcolumnwidth}{\maincolumnwidth-\listitemsymbolwidth}%
   \setlength{\doubleitemcolumnwidth}{\maincolumnwidth-\hintscolumnwidth-\separatorcolumnwidth-\separatorcolumnwidth}%
   \setlength{\doubleitemcolumnwidth}{0.5\doubleitemcolumnwidth}%
+  \setlength{\tripleitemcolumnwidth}{\maincolumnwidth-\hintscolumnwidth-\hintscolumnwidth-\separatorcolumnwidth-\separatorcolumnwidth-\separatorcolumnwidth}%
+  \setlength{\tripleitemcolumnwidth}{0.33\tripleitemcolumnwidth}%
   \setlength{\listdoubleitemcolumnwidth}{\maincolumnwidth-\listitemsymbolwidth-\separatorcolumnwidth-\listitemsymbolwidth}%
   \setlength{\listdoubleitemcolumnwidth}{0.5\listdoubleitemcolumnwidth}%
   \recompute@cvskillmatrix@lengths
@@ -97,6 +101,19 @@
     \hspace*{\separatorcolumnwidth}%
     \begin{minipage}[t]{\doubleitemcolumnwidth}#5\end{minipage}}}
 
+\renewcommand*{\cvtripleitem}[7][.1em]{%
+  \cvitem[#1]{#2}{%
+    \begin{minipage}[t]{\tripleitemcolumnwidth}#3\end{minipage}%
+    \hfill% fill of \separatorcolumnwidth
+    \begin{minipage}[t]{\hintscolumnwidth}\raggedleft\hintstyle{#4}\end{minipage}%
+    \hspace*{\separatorcolumnwidth}%
+    \begin{minipage}[t]{\tripleitemcolumnwidth}#5\end{minipage}%
+    \hspace*{\separatorcolumnwidth}%
+    \begin{minipage}[t]{\hintscolumnwidth}\raggedleft\hintstyle{#6}\end{minipage}%
+    \hspace*{\separatorcolumnwidth}%
+    \begin{minipage}[t]{\tripleitemcolumnwidth}#7\end{minipage}}}
+
+
 \renewcommand*{\cvlistitem}[2][.25em]{%
   \cvitem[#1]{}{\listitemsymbol\begin{minipage}[t]{\listitemcolumnwidth}#2\end{minipage}}}
 
diff --git a/template.tex b/template.tex
index 22be6f0..c2ccabd 100644
--- a/template.tex
+++ b/template.tex
@@ -158,6 +158,7 @@ Detailed achievements:
 \cvdoubleitem{category 1}{XXX, YYY, ZZZ}{category 4}{XXX, YYY, ZZZ}
 \cvdoubleitem{category 2}{XXX, YYY, ZZZ}{category 5}{XXX, YYY, ZZZ}
 \cvdoubleitem{category 3}{XXX, YYY, ZZZ}{category 6}{XXX, YYY, ZZZ}
+\cvtripleitem{category 4}{XYZ}{category 5}{XYZ}{category 6}{XYZ}
 
 \section{Skill matrix}
 \cvitem{Skill matrix}{Alternatively, provide a skill matrix to show off your skills}
```

If this helps I also could push it to a separate branch of my moderncv fork or create a PR.

**Nevertheless** for my taste it is a bit too much having three columns, but this should be decided by others and is more a matter of taste.  
Also I am not sure if I should implement it as a new feature branch. What does others think of it? Feel free to comment and discuss. :)

**Comment by djrmarques** [comment]
Hello. Thanks a lot! Yeah, I agree with you, for most use cases having 3 columns is too much, but I have one specific section on my CV where I would like to have it (basically the spoken languages section). I would allow me to save some vertical space. 

In any case, I would think such a command could be added to the branch code, but of course that's it not up to me to decide. 

Thanks a lot for the git diff!

**Comment by djrmarques** [comment]
@LLdaniel sorry to bother you again with this, but could you add the `diff` header to the code block you sent above? I just makes it much easier to read :nerd_face: . Seems like it [works](https://stackoverflow.com/questions/40883421/diff-syntax-highlighting-in-github-markdown).

**Comment by LLdaniel** [comment]
Ahh, nice, didn´t know that this works also for `diffs`. Thanks! 💡
I edited my original comment. Maybe I will find some time over the weekend and will create a pull request also for other styles. In the meantime you could also have a look at my fork. There I created a separate branch: [moderncv_mod feature/cvtripleitem](https://github.com/LLdaniel/moderncv_mod/tree/feature/cvtripleitem)
