### ISSUE TITLE
Align personal data

### ISSUE THREAD

**Issue by quocan91tc** [moderncv/moderncv#180]
**Is your feature request related to a problem? Please describe.**
Hello,
Thank for your great work. Could I align the personal data to the left and the recipient info to the right, if it is possible then how to make change, please? 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LLdaniel** [comment]
Hi @quocan91tc ,
I am not sure which style you are using. I am assuming the "classic" style. 
As far as I understand your changes you wanted to switch sides in the cover letter, right?

Here a quick and dirty attempt to switch sides using the default `template.tex`:
```diff
diff --git a/moderncvheadi.sty b/moderncvheadi.sty
index 346bf12..e37b3d5 100644
--- a/moderncvheadi.sty
+++ b/moderncvheadi.sty
@@ -163,10 +163,10 @@
   \recomputeletterlengths%
   % sender contact info
   \hfill%
-  \begin{minipage}{.5\textwidth}%
+  \begin{minipage}{\textwidth}%
     % optional detailed information
     \if@details%
-      \raggedleft%
+      \raggedright%
       \addressfont\textcolor{color2}{%
         {\bfseries\upshape\@firstname~\@lastname}\@firstdetailselementfalse%
         % optional detailed information
@@ -181,8 +181,8 @@
         \ifthenelse{\isundefined{\@extrainfo}}{}{\makenewline\@extrainfo}}\fi%
     \end{minipage}\\[2em]
   % recipient block
-  \begin{minipage}[t]{.5\textwidth}
-    \raggedright%
+  \begin{minipage}[t]{\textwidth}
+    \raggedleft%
     \addressfont%
     {\bfseries\upshape\@recipientname}\\%
     \@recipientaddress%

```
Hope this guides you in the correct direction. 
![Screenshot from 2024-03-26 21-55-35](https://github.com/moderncv/moderncv/assets/41345639/f9ea49e7-17e8-492e-a078-fd1185f14df8)

**Comment by LLdaniel** [comment]
> Could you please give me a little more instruction of how to apply your code to template.txt file, please?

Ah, now I see: I wrote something about the `template.tex` and pasted my changes of `moderncvheadi.sty` directly beneath it. Currently there is no way to change it directly in your `template.tex`. You have to edit the `.sty` file.

So here is a way to go with hopefully a bit more instructions (could be dependent on your sepcific LaTeX setup):
1. Download the Code of this repo to a working directory as you wish (manually or for example with `git clone https://github.com/moderncv/moderncv.git`)
2. When using the "classic" style: Modify the `moderncvheadi.sty` file so it corresponds to my above posted `diff` that is:
* lines with a minus is the current state of your `moderncvheadi.sty` now
* find the sections given by the line numbers in purple color
* change the lines with the minus in such a way that they match the lines with plus, i. e. 
```diff
@@ -1 +1 @@
-this is an example
+this is the changed version
```
*Meaning: Go to line 1 and change it from "this is an example" to "this is the changed version"*

**My Setup**
TeX Live on Ubuntu 22.04., simply cloned the moderncv code to a working directory, changed the `moderncvheadi.sty` there and compiled `template.tex` with `pdflatex`.
This may vary for you depending on your LaTeX distribution and OS. Just wanted to give additional information why the above steps are working for me.

**Comment by quocan91tc** [comment]
Hi @LLdaniel ,

Sorry for my late respond. Thank you very much, it work. I simply downloaded the `moderncvheadi.sty`, made change in there and then import to my `.tex` file with` \usepackage{moderncvheadi.sty}`.

Have a nice Easter,

<img width="585" alt="Capture d’écran 2024-04-01 à 11 34 17" src="https://github.com/moderncv/moderncv/assets/32663314/77ddefc6-1bd8-483b-a1dc-d1d81124143f">
