### ISSUE TITLE
Custom colors are not showing anymore...

### ISSUE THREAD

**Issue by sami-akkawi** [moderncv/moderncv#198]
**Describe the bug**
After the updating through the TeX Live Utility. All colors are not being considered neither are the font weights.

**Expected Behavior**
The defined color0, color1 and color2 still work as before.

**Actual Behavior**
No colors are being considered, everything is balck. Neither are the font weights (especially the name)

**Minimum Working Example to Reproduce the Problem**
I have this defined, but they are not being implemented

\definecolor{color0}{HTML}{000000}
\definecolor{color1}{HTML}{1183c6}
\definecolor{color2}{HTML}{737373}

**Specifications**
  - moderncv version and source: the latest
  - LaTeX compiler (pdfLaTeX, XeLaTeX, etc.) and version: pdfLaTeX
  - Platform (operating system, LaTeX editor, etc.): Both MacOS and Windows 11

**Additional context**

**Comment by LLdaniel** [comment]
Hi @sami-akkawi ,
Do you have a minimal example `.tex` for me were your color definition is not working anymore? This would help me in reproducing your issue. 

In the meantime I used the `template.tex` (only added `.txt` suffix for GitHub upload) and changed the color definition to match your example: 
It looks like this and seems to accept the colors:
[template_customColor.pdf](https://github.com/user-attachments/files/16336347/template_customColor.pdf)
[template.tex.txt](https://github.com/user-attachments/files/16336405/template.tex.txt)
(compiled with TeX Live 2022/Debian, LuaHBTeX, Version 1.15.0 or pdfTeX 3.141592653-2.6-1.40.24)

Introduced with #151, there is also the ability to change the color of some special parts like the name, skillmatrix etc. Please have a look into the new manual, chapter 3.2.

**Comment by LLdaniel** [comment]
Thanks for your minimal example:
Due to the breaking changes of the color adjustments in the above linked PR the `\moderncvcolor` has to be set before the `\moderncvstyle`. The colors has to be one of the first things to be set up, because of all the other macros using them. 

Therefore I would recommend to create a `moderncvcolorcustom.sty` with only the color definitions like this:
```tex
%% start of file `moderncvcolorcustom.sty'.
%% EN

%-------------------------------------------------------------------------------
%                Color Scheme Definitions
%-------------------------------------------------------------------------------
\definecolor{color0}{HTML}{000000}
\definecolor{color1}{HTML}{1183c6}
\definecolor{color2}{HTML}{737373}

\endinput
%% end of file `moderncvcolorcustom.sty'.
```
All other adjustments have to go into a separate file to be called after the `moderncvstyle`. 
Either you create your own derived style from casual or maybe include the rest as `adjustments.tex` like this:
```tex
% Beginning of file `CoverLetter.tex`.
\documentclass[11pt,a4paper]{moderncv}

% first the color scheme has to be set, beware that \hintscolumnwidth etc are undefined at this point
\moderncvcolor{custom}
% moderncv themes config: either create your own moderncvstyle "custom"...-----|
\moderncvstyle{casual}%                                                        |
%\moderncvcolor{custom}                                                        |
% ... or maybe include your adjustments just with input: ----------------------|
\include{adjustments}

%--------------------------------------------------------------------------------
%            Contact Information
%--------------------------------------------------------------------------------
%Titel
\title{Cover Letter} 
%Quote
%\quote{Any fool can write code that a computer can understand.\\Good programmers write code that humans can understand.\\\textbf{M. Fowler}}

%--------------------------------------------------------------------------------
%            Content
%--------------------------------------------------------------------------------

\begin{document}
\maketitle

\myreceiver[Receiver]{Address}
\\ \\ \\
\Today
\newline
\section{Title}
\vfill
Text text text
\vfill
\vfill
\vfill
\vfill
\vfill
\end{document}

% End of file `CoverLetter.tex`.
```

This produced the following `.pdf` then:
[CoverLetter.pdf](https://github.com/user-attachments/files/16351876/CoverLetter.pdf)

I hope this helps.

**Comment by sami-akkawi** [comment]
This actually worked! Thank you very mich @LLdaniel !!!
