### ISSUE TITLE
File `moderncvcolors.tex' not found

### ISSUE THREAD

**Issue by krysros** [moderncv/moderncv#199]
**Describe the bug**
Unable to compile document after updating to version 2.4.1.

**Actual Behavior**

```console
PS C:\Users\Krystian\Dokumenty\CV> pdflatex cv_Krys_Ros
This is pdfTeX, Version 3.141592653-2.6-1.40.26 (MiKTeX 24.4) (preloaded format=pdflatex.fmt)
 restricted \write18 enabled.
entering extended mode
(cv_Krys_Ros.tex
LaTeX2e <2024-06-01> patch level 2
L3 programming layer <2024-05-27>
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/moderncv\moderncv.cls
Document Class: moderncv 2024-07-18 v2.4.1 modern curriculum vitae and letter d
ocument class
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/base\size11.clo)
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/etoolbox\etoolbox.sty)
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/base\ifthen.sty)
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/xcolor\xcolor.sty
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/graphics-cfg\color.cfg)

(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/graphics-def\pdftex.def
)
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/graphics\mathcolor.ltx)
) (C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/colortbl\colortbl.sty
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/tools\array.sty))
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/generic/iftex\iftex.sty)
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/url\url.sty)
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/base\fontenc.sty)
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/graphics\graphicx.sty
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/graphics\keyval.sty)
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/graphics\graphics.sty
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/graphics\trig.sty)
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/graphics-cfg\graphics.c
fg)))
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/fancyhdr\fancyhdr.sty)
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/moderncv\tweaklist.sty)
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/tools\calc.sty)
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/l3packages/xparse\xpars
e.sty
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/l3kernel\expl3.sty
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/l3backend\l3backend-pdf
tex.def)))
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/microtype\microtype.sty

(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/microtype\microtype-pdf
tex.def)
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/microtype\microtype.cfg
))
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/moderncv\moderncvcollec
tion.sty)
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/moderncv\moderncvcompat
ibility.sty))
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/geometry\geometry.sty
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/generic/iftex\ifvtex.sty)
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/geometry\geometry.cfg))
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/base\inputenc.sty)
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/base\fontenc.sty)
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/lm\lmodern.sty)
(C:\Users\Krystian\AppData\Local\Programs\MiKTeX\tex/latex/moderncv\moderncvcolorb
lack.sty

! LaTeX Error: File `moderncvcolors.tex' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: tex)

Enter file name:
```

**Minimum Working Example to Reproduce the Problem**

Any example. You can use the template provided here https://github.com/moderncv/moderncv/issues/198#issuecomment-2243283409.

**Specifications**
  - moderncv version and source: 2.4.1
  - LaTeX compiler (pdfLaTeX, XeLaTeX, etc.) and version: pdfLaTeX, XeLaTeX, LuaLaTeX
  - Platform (operating system, LaTeX editor, etc.): Windows 11, MiKTeX 24.1

**Comment by krysros** [comment]
Workaround:

Copy the https://github.com/moderncv/moderncv/blob/master/moderncvcolors.tex file to your CV directory.

**Comment by hudcap** [comment]
More general workaround:
Put the file in the `moderncv` package directory (for me, `...\AppData\Local\Programs\MiKTeX\tex\latex\moderncv`) and then refresh the file name database.

Looks like the file is in CTAN, but not in the list of files on MiKTeX. My best guess is that MiKTeX ignores `.tex` files, although I have no source for this.
Perhaps renaming it to `moderncvcolors.sty` would resolve this?

**Comment by hudcap** [comment]
Can confirm that there is a package in MiKTeX called `moderncv__source` that includes `moderncvcolors.tex` (along with the changelog, `template.tex`, etc.)
Seems my hunch is correct, but there might be a better way to flag the file as part of the package—hard to find info on this online.

**Comment by LLdaniel** [comment]
Thanks for your research, @hudcap. I do not have much experience with MiKTeX. Therefore I also have no other way to flag a runtime relevant `.tex` file as such. With MiKTeX/miktex/discussions/1511 I try to learn a bit more about the directory structure. 

Nevertheless will open a PR, which renames the `moderncvcolors.tex` to `moderncvcolors.sty` and includes it accordingly. Hopefully this will help MiKTeX users to successfully compile documents again. Thanks for the provided workaround (also to @krysros).

**Comment by williamhbell** [comment]
> Workaround:
> 
> Copy the https://github.com/moderncv/moderncv/blob/master/moderncvcolors.tex file to your CV directory.

Having done this, `color1` does not change the colour of the bar as suggested by https://stackoverflow.com/questions/64537863/how-to-change-color-of-the-bar-in-moderncv-latex.

- `color0` changes the text colour as expected.
- `color1` changes the bullet colours, but does not change anything else.
- `color2` has no effect on any of the content.

I am using the latest MikTeX with moderncv 2.4.1.

**Comment by LLdaniel** [comment]
Hi @williamhbell ,
> Having done this, color1 does not change the colour of the bar as suggested by https://stackoverflow.com/questions/64537863/how-to-change-color-of-the-bar-in-moderncv-latex.

With 2.4.X we introduced a feature to allow more fine tuned color adjustments. If I am understanding you correctly you try to change the color of the section bar in "casual" style. 
This can be done with:
```latex
\colorlet{bodyrulecolor}{red}
```
somewhere in your preamble after 
```latex
\moderncvcolor{blue}
\moderncvstyle[]{casual}
```
You may also want to change the color of the sections or even subsections. To do this just add:
```latex
\colorlet{sectioncolor}{red}
\colorlet{subsectioncolor}{red}
```

If you want to play more with colors feel free to check chapter 3.2 in the user manual.

**Comment by krysros** [comment]
There is already an update of the moderncv package with the same version number available in MiKTeX Console. In my case, compilation works fine (without using workarounds).

**Comment by hudcap** [comment]
I am seeing the same as @krysros, however I noticed that this is not actually the new version following #200, but rather the version before that commit (using the `.tex`) extension, and the file is now included properly in the installation. Not sure how that happened—did someone fix this with MiKTeX?

**Comment by LLdaniel** [comment]
Interesting. Self solving problems that´s cool :sweat_smile: 
Good to know that it is working now also for MikTeX users. The only thing I know is that everything was fine on CTAN with 2.4.1. 

Nevertheless from my side I will leave it now as a `.sty` file, because every other file is also a `.sty`. Seems to be more consistent then. 
I should have created a new release with the `moderncvcolors.sty` included, but if this is not that urgent anymore I will postpone that until a future release.
