### ISSUE TITLE
Disabling `\photo` produces an error

### ISSUE THREAD

**Issue by pcotret** [moderncv/moderncv#201]
**Describe the bug**
I was using the default template available [here](https://github.com/moderncv/moderncv/blob/master/template.tex) and I would like to remove the `\photo` from the file.

**Expected Behavior**
A header without photo on the left side of the PDF.

**Actual Behavior**
Got an error at compile time:
```bash
! Undefined control sequence.
<argument> \@photoframewidth 
                             
l.130 \makecvtitle
```

**Minimum Working Example to Reproduce the Problem**
Just comment https://github.com/moderncv/moderncv/blob/master/template.tex#L111 in the example LaTeX file.

**Specifications**
- moderncv, commit 34e7b15a6bc41a2fa1af3b8657ecec498b3a7470.
- pdfTeX 3.141592653-2.6-1.40.24 (TeX Live 2022/Debian)
- (Similar issue with Overleaf online)

**Comment by pcotret** [comment]
here is a workaround in the meantime:
```tex
\photo[0pt][0pt]{picture} 
```

**Comment by LLdaniel** [comment]
Thanks @pcotret for your detailed report and workaround. 
Can confirm the error (LuaHBTeX, Version 1.15.0, TeX Live 2022/Debian).

I will have a look into that. It seems that this is only an issue with the contemporary style.

**Comment by paddyroddy** [comment]
> here is a workaround in the meantime:
> 
> ```
> \photo[0pt][0pt]{picture} 
> ```

Thanks, @pcotret! Was also stuck on this one
