### ISSUE TITLE
Long names do not get split anymore

### ISSUE THREAD

**Issue by AlexVonB** [moderncv/moderncv#220]
**Describe the bug**

With a long name that usually would be split in two lines, when using `\makecvtitle` a non-breaking space `~` is used to separate first and last name. This was introduced by

https://github.com/moderncv/moderncv/commit/08371bb3e235152e3dac2c6c8faef659777c5543#diff-96653b6262ff68b98bcc257130604ac8e4ab4e7a865fc13d0cc2663bfaceac61L121

**Expected Behavior**

Long names should be allowed to break into two lines when using `\makecvtitle`. This was possible before the change linked above (`\ ` instead of `~`)

**Actual Behavior**

The name gets rendered as `Firstname~Lastname` and does not break if needed.

**Minimum Working Example to Reproduce the Problem**

Classic style, long first and last name.

**Specifications**
  - moderncv version and source: 2.4.1 (latest version on CTAN, should be the same on master)
  - LaTeX compiler (pdfLaTeX, XeLaTeX, etc.) and version: pdfTeX 3.141592653-2.6-1.40.26
  - Platform (operating system, LaTeX editor, etc.): Ubuntu (WSL)

**Workaround**

`\renewcommand*{\lastnamestyle}[1]{{\namefont\textcolor{lastnamecolor}{\ #1}}}` just before `\makecvtitle`

Thanks for maintaining this! :)

**Comment by LLdaniel** [comment]
Thanks for your report and analysis, @AlexVonB, and also for providing a workaround as well. 
We probably should switch back to `\ ` instead of an unbreakable space with `~`. This would help to support longer names again.
