### ISSUE TITLE
expand marvosym icons

### ISSUE THREAD

**Issue by mefuller** [moderncv/moderncv#26]
Identify social icons which are only available with awesome (and by extension Xe/Lua(La)Tex) and add alternatives to marvosym

**Comment by wwywong** [comment]
See also https://github.com/moderncv/moderncv/issues/81#issue-1072563708

`fontawesome5` works with pdflatex. So the more crucial set is the (somewhat smaller) set of 124 icons from `academicons`.

**Comment by LLdaniel** [comment]
This task seems to be completed. Therefore I will close this issue.
