### ISSUE TITLE
CI Integration

### ISSUE THREAD

**Issue by stephanlachnit** [moderncv/moderncv#4]
For example something like https://github.com/xdanaux/moderncv/pull/87.

**Comment by stephanlachnit** [comment]
Maybe also relevant: https://github.com/xdanaux/moderncv/pull/55

Minus the gitignore and trailing whitespaces

**Comment by stephanlachnit** [comment]
Also possible, building with latexmk and scanning with texloganalyser (https://www.ctan.org/tex-archive/support/texloganalyser?lang=en, https://packages.debian.org/search?mode=path&suite=sid&section=all&arch=any&searchon=contents&keywords=texloganalyser).

**Comment by stephanlachnit** [comment]
@ShadowMitia now that we have a CI, we should only do PRs when changing code instead of committing directly to ensure that we don't introduce any new warnings (right now there are 107 warnings).

**Comment by ShadowMitia** [comment]
@stephanlachnit Will do!
