### ISSUE TITLE
PdfTeX: one cannot use anything but the utf8 input encoding

### ISSUE THREAD

**Issue by fstengel** [moderncv/moderncv#40]
Which is silently loaded by default (see line 115 of moderncv.cls). Why is that so? Why is it that the documentation makes no mention of this and even hints one can choose the proper encoding (see p. 2 top and the example in section 2.1)?

**Comment by stephanlachnit** [comment]
The documentation is outdated. And I don't why it is loaded by default.

**Comment by fstengel** [comment]
Thanks. I gathered as much for the documentation.
The thing is, I do not see the point of lines https://github.com/moderncv/moderncv/blob/09d62474db024c653a29874306c9e1d19d7ed77a/moderncv.cls#L102-L125
They only do something if one is *not* using /xe/lua/TeX when the comment placed just before indicates they were put to solve an issue when one was using /xe/lua/TeX.
So this beaks moderncv if one does not use unicode input encoding  (show stopper: only one input encoding is allowed) and T1 fontencoding (not too bad: one can set the encoding more than once)

**Comment by mefuller** [comment]
Possible relation to #35?

**Comment by pacho2** [comment]
It looks like https://github.com/moderncv/moderncv/issues/36

**Comment by stephanlachnit** [comment]
You can change the encoding here if you don't use Latex/Xetex:
https://github.com/moderncv/moderncv/blob/0095e75df4dd07df7d1f468ad142b975d782109e/template.tex#L17-L19
