### ISSUE TITLE
pdflatex (MacTex on MacOS) pulls the wrong version

### ISSUE THREAD

**Issue by Xaelias** [moderncv/moderncv#42]
Hi!
I'm sorry to be asking here, and it's probably just my own ignorance (I'm just coming back to LaTeX, I've forgotten a lot!), but I see that this package is now in version 2.1, but my local install seem to only be pulling the 2.0 version.
I assume I can just clone the repo locally and force it to use that but it's less than ideal.

What am I missing?
Thanks
Alexis

```
❯ latex --version
pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020)
kpathsea version 6.3.2
Copyright 2020 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.02
```

**Comment by stephanlachnit** [comment]
This is not an issue here, sorry. Your LaTeX distribution needs to be updated, I never used LaTeX on a Mac, so I can't help you. The latest version is on CTAN and correctly pulled by other LaTeX distributions like TeXLive.

**Comment by Xaelias** [comment]
Fair enough.  
If anybody lands here with the same problem, I ran the following commands to solve it:
```

```
It... took a while. There were almost 1,000 things to upgrade.  
And it f*ed up a bunch of other things. I'm missing icons and my links are not rendered properly anymore... But I got moderncv 2.1 I guess.
