### ISSUE TITLE
Process Exited with errors

### ISSUE THREAD

**Issue by goodsamannan** [moderncv/moderncv#61]
I downloaded the package from [https://ctan.org/pkg/moderncv?lang=en](url) but when I try to run in TeXStudio on my macOS Big Sur, I get the error shown in the attached image. Will be glad if you assist. 
<img width="651" alt="Screenshot 2021-06-06 at 10 52 43 PM" src="https://user-images.githubusercontent.com/65621491/120942772-96eb1d00-c71a-11eb-8fc5-4b1e8bcfe12d.png">

**Comment by stephanlachnit** [comment]
This is not an issue with moderncv. It seems like your TeXLive setup is not working properly (`getcwd: Operation not permitted`). This might help you to fix this issue: https://tex.stackexchange.com/questions/511617/error-with-pdftex-after-updating-to-mac-os-catalina

**Comment by goodsamannan** [comment]
Hello @stephanlachnit. I did the settings change and everything works fine. Permit me to ask this. How sure can we be granting "**Full Disk Access**" to **TeXStudio** is innocuous?

**Comment by stephanlachnit** [comment]
Well, you can take a look at the source code on github: https://github.com/texstudio-org/texstudio

But tbh you don't really need to, there are enough people that would notice if TeXstudio would touch any other data on your disk than it should. Of course, you don't just need to trust the source code, but also the binary you downloaded (assuming you didn't build TeXstudio yourself). But again, assuming that you didn't download it from a sketchy website, there should be no problem.
