### ISSUE TITLE
Undefined control sequence due to \born command

### ISSUE THREAD

**Issue by jvosantos** [moderncv/moderncv#62]
On a system with the packages required installed as well as the moderncv package, on a folder with just the following files:
- template.tex
- publications.bib
- picture.eps
- picture.jpg

When trying to generate a pdf with the command:
`latexmk -pdf template.tex`

it fails due to the `\born` command:
```
! Undefined control sequence.
l.29 \born
          {4 July 1776}                                 % optional, remove /...
```

full output in file [born-error-output.txt](https://github.com/moderncv/moderncv/files/6734276/born-error-output.txt)
malformatted pdf output in file [born-error-output.pdf](https://github.com/moderncv/moderncv/files/6734310/born-error-output.pdf)

Commenting out [L29](https://github.com/moderncv/moderncv/blob/master/template.tex#L29) seems to do the trick.

successful output in file [success-output.txt](https://github.com/moderncv/moderncv/files/6734349/success-output.txt)
successful pdf in file [success-output.pdf](https://github.com/moderncv/moderncv/files/6734350/success-output.pdf)

PS: I'm not compiling the template.tex example inside the moderncv repo as stated in the beggining, the moderncv was installed using tlmgr.

```
$ tlmgr info moderncv
package:     moderncv
category:    Package
shortdesc:   A modern curriculum vitae class
longdesc:    The class provides facilities for typesetting modern curriculums vitae, both in a classic and in a casual style. It is fairly customizable, allowing you to define your own style by changing the colours, the fonts, etc. The template.tex file can be used as an example.
installed:   Yes
revision:    57496
sizes:       doc: 465k, run: 325k
relocatable: No
cat-version: 2.1.0
cat-license: lppl1.3c
cat-topics:  cv class
cat-contact-repository: https://github.com/moderncv/moderncv.git
cat-contact-home: https://github.com/moderncv/moderncv
cat-contact-development: https://github.com/moderncv
cat-contact-bugs: https://github.com/moderncv/moderncv/issues
collection:  collection-latexextra
```

**Comment by MartinX3** [comment]
Getting the same error with Tex Live 2021 and Lualatex

**Comment by stephanlachnit** [comment]
Thanks, I can confirm this with TeXLive `2020.20210202`.

**Comment by stephanlachnit** [comment]
Actually no, this is not an issue. The born command was added after v2.1.0, so it's not included in a release yet.
