### ISSUE TITLE
`\moderncvstyle{fancy}` broken?

### ISSUE THREAD

**Issue by MartinX3** [moderncv/moderncv#63]
If I try `\moderncvstyle{fancy}`, it tells me, that a `}` at the \cventry is too much, (which is wrong).
All other styles are working.

**Comment by stephanlachnit** [comment]
Can you post a minimum example for this?

**Comment by MartinX3** [comment]
Thank you for your response.

I found my mistake.
In `\cventry` I used `\\` for a newline, instead of `\newline{}`
I wonder why only the `fancy` still triggered the error, but it works now at my site. :)
