### ISSUE TITLE
Icon switch to better follow previous fontawesome style

### ISSUE THREAD

**Issue by milouse** [moderncv/moderncv#67]
Hi all and thank you very much for your work to continue to support this nice package.

Lately, I was working on my curriculum and noticed the change from fontawesome to fontawesome5 (as a tex package maintainer myself, I see no problem there and agree the need to depend on well maintained packages).

However, as noticed in #20 and the related issue #19 that change push solid-looking icon where previously we add shape only ones. After a quick test on my own, I would like to suggest the following changes to make the switch to fontawesome5 almost invisible (i.e. use regular style when possible):

```latex
\renewcommand*{\labelitemi}{\strut\textcolor{color1}{\tiny\faCircle[regular]}}
\renewcommand*{\emailsymbol}{{\small\faEnvelope[regular]}~}
\renewcommand*{\homepagesymbol}{{\small\faGlobeAmerica}~} % alternative: \faGlobeEurope, \faGlobeAsia…
\renewcommand*{\mobilephonesymbol}{{\small\faMobile*}~}
\renewcommand*{\linkedinsocialsymbol}{{\small\faLinkedinIn}~}
```

Here is the rendering without my adjustements:

![before_change](https://user-images.githubusercontent.com/349239/128636566-ee0c342b-803a-4bbc-a61a-c4c382c75944.png)

And after my proposal, how it looks like:

![after_changes](https://user-images.githubusercontent.com/349239/128636564-14d2fcf4-6a76-4ea7-be37-4fe364882626.png)

For memory purpose, here is the same snippet, as it appear on an old generated pdf (before switch to fontawesome5):

![Capture du 2021-08-08 16-54-44](https://user-images.githubusercontent.com/349239/128636567-67bebccf-610c-43ce-8572-943617a8b5df.png)

What do you think?

**Comment by milouse** [comment]
If we find an agreement, I’d open a PR :)

**Comment by ShadowMitia** [comment]
I don't really mind either way, but one of the issues I reported #20 was keeping the old style wasn't possible, because it's behind PRO features. 

Again I don't mind either way, but we'd lost consistency in the icons (at least out of the box), which isn't great. In your example it works fine, but maybe with other icons it won't work as well out of the box. And even then it's very subjective.

But you do raise a valid point, maybe we should have a way to more easily change stylings?

**Comment by stephanlachnit** [comment]
I prefer the looks as well, thanks for opening an issue. I was able to reproduce it with TeXLive on Debian Sid, so at least the icons you listed work find. You had a typo though, it's `\faGlobeAmericas` not `\faGlobeAmerica`.

Feel free to open a PR. If you can, please take a look at the template and try to find icons that are consistent with the looks for all of them. You can find a list in the documentation: https://ftp.mpi-inf.mpg.de/pub/tex/mirror/ftp.dante.de/pub/tex/fonts/fontawesome5/doc/fontawesome5.pdf
