### ISSUE TITLE
Remove period after item

### ISSUE THREAD

**Issue by F0Xde** [moderncv/moderncv#68]
Is it possible to remove the full stop that is inserted after each item?

**Comment by ShadowMitia** [comment]
There's no out-of-the-box way to to do this but there are a few items [here](https://tex.stackexchange.com/questions/241093/moderncv-cventry-remove-dots-at-the-end-of-line/457896) that might be useful.

There seems to be a lot of posts about configuring this, maybe it's something that should be customisable somehow.

**Comment by stephanlachnit** [comment]
Since I disliked the dot as well, I removed it in f9c1836eb6367e986b0a13cd4adff7a6c4a6ff8e, which is included in the v2.2.0 release, which you can find on CTAN.
