### ISSUE TITLE
Should we define the input encoding?

### ISSUE THREAD

**Issue by ikp123** [moderncv/moderncv#73]
Tried to compile this sample code on my machine using xelatex (W10, new installation of miktex).

It gave an error " LaTeX Error: Command `\eth' already defined". 

Here is the code:
\documentclass[english,12pt,a4paper,roman]{moderncv} 

%% math and physics packages:
\usepackage{amsmath}
\usepackage{amssymb}

\usepackage[english]{babel}

%\usepackage{mathspec} % conflicts with 'unicode-math'
%\usepackage{fontspec} % is loaded automatically by 'unicode-math'

\RequirePackage{unicode-math}
\setmainfont{Calibri}
\setmathfont{Latin Modern Math}

\begin{document}
Hello World.
\end{document}

(Pretty sure it's moderncv's fault here, because when I change to article, everything works)

**Comment by stephanlachnit** [comment]
If you want to use XeTeX (or LuaTeX) with proper unicode for math, use this:

```LaTeX
\usepackage{fontspec} % optional to load, but if do it before unicode-math, don't load mathspec

\usepackage{amsmath}  % for math commands
\usepackage{unicode-math}  % for math symbols, use instead of amssymb

\setmainfont{Calibri}
\setmathfont{Latin Modern Math}
```


I think the error is because you use

```LaTeX
\usepackage{amssymb}
\RequirePackage{unicode-math}
```

`RequirePackage` will just result in `unicode-math` being loaded. However the goal of `unicode-math` is to use unicode symbols in math mode. However afaik, `amssymb` conflicts with that as it doesn't work that way. If you use `unicode-math`, you can essentially drop `amssymb`. There are minor differences between the two packages, and in case you need something from `amssymb`, don't load `unicode-math`.

**Comment by stephanlachnit** [comment]
Ah, I missed the part where you state the article works fine. I think in this case `RequirePackage` probably shouldn't do anything, but I'm not sure. Using `amssymb` and `unicode-math` should clash.

Look here:

https://github.com/moderncv/moderncv/blob/167c9e439524ea5ba9c6f1a4f0ab764c7f433cf0/moderncv.cls#L99-L113

When loading `moderncv` with XeTeX or LuaTeX, `unicode-math` will be loaded.

Btw I'll suggest not to use Calibri in MWEs as it is non-free and not everyone can test it.

**Comment by ikp123** [comment]
I posted a question on stack exchange, https://tex.stackexchange.com/questions/614961/moderncv-and-xelatex-command-definition-clash. The problem is that moderncv already defines some symbols that amssymb defines as well. 
Also, it has something to do with moderncv being updated lately (July, I think), because this wasn't a problem before the update.

About the font, you can change Calibri to any font, it won't matter.

**Comment by stephanlachnit** [comment]
Yes so as I said.

The question is if we should do this at all or not. I'm still convinced, that the definition we do is correct. However, the real question is whether or not we should define a font at all.

**Comment by ikp123** [comment]
OK, the best solution would be one that would "just work", regardless of the author uses amssymb, xelatex, etc. Another option is to add an explanation of a work around in the official package manual.
