### ISSUE TITLE
Provide example usage of `\moderncv(head|body|tail|icons){n}`

### ISSUE THREAD

**Issue by Esgariot** [moderncv/moderncv#78]
Changelog mentions addition of `\moderncvhead`, `\moderncvbody`, `\moderncvfoot` and `\moderncvicons`, but I can't seem to find usage instructions for them. Without much tex knowledge I didn't know where to put them and had to try at random to see what works.

**Comment by LLdaniel** [comment]
A better documentation will be delivered with the reworked user guide (cf. 1462709fd7bb2e566fe4f55ee8e579e4ea1445ce)

**Comment by LLdaniel** [comment]
This is now clarified in the new `moderncv_userguide.pdf`, see chapter 4.1 "Creating your own styles".
