### ISSUE TITLE
Wrong usage of \detokenize breaks all commands and active characters in the text argument of \link etc.

### ISSUE THREAD

**Issue by komascript** [moderncv/moderncv#79]
You've defined `\link` as
```latex
\newcommand*{\link}[2][]{%
  \ifthenelse{\equal{#1}{}}%
    {\href{#2}{#2}}%
    {\href{#2}{\detokenize{#1}}}}
```
Similar for all other commands, that internally use `\href`.

With this, something like:
```latex
\newcommand*{\test}{This is an often used text.}
\link[\test]{http://some.link.invalid}
```
is not possible (or would result in the not expected string `\test` in the output).

Moreover with pdfLaTeX all non US-ASCII-characters will break and even TeX commands for accents umlauts etc. break, e.g.
```latex
\documentclass[a4paper,11pt]{moderncv}
\moderncvstyle{casual}
\moderncvcolor{blue}

\usepackage[ngerman]{babel}
\usepackage[T1]{fontenc}
\usepackage{inputenc}
\usepackage[paper=a4paper,left=20mm,right=10mm,top=10mm,bottom=20mm]{geometry}
\firstname{John}
\familyname{Doe}

\begin{document}
\cvitem{10/2020 03/2021}{\textbf{Hilfreiche Links} \newline
\httplink[Göögle.com]{www.google.com} \newline
\httplink[Sehr hilfreich für Probleme]{golatex.de} \newline
\httplink[Sehr hilfreich f{\"u}r Probleme]{golatex.de} \newline
}
\end{document}
```
results in broken Umlauts like:
```
GÃűÃűgle.com
Sehr hilfreich fÃijr Probleme
Sehr hilfreich f{\"u}r Probleme
```
instead of the expected:
```
Göögle.com
Sehr hilfreich für Probleme
Sehr hilfreich für Probleme
```

IMO here the `\detokenize` does not make much sense, because the user would expect more, that commands work than that an underscore can be given by `_` instead of the usual LaTeX underscore character command `\_`.

Moreover, it makes no sense, that `\httplink[john_doe]{somewhere.invalid}` should work but `\httplink{somehwere.invalid/john_doe}` doesn`t.

So please remove all these `\detokenize`. They break more than they help.

BTW: Can you please add some explicit information to the manual, that the mandatory argument of `\httplink`, `\httpslink` etc. should be without the prefix `http://` etc. Because currently this information is only implicit from the example. Furthermore the command `\weblink` shown in the manual is not defined. Instead this is `\link`, which is not documented in the manual.

BTW: @ethuleau has already reported the issue [here](https://github.com/moderncv/moderncv/issues/23#issuecomment-877213645). But you've closed the whole issue without fixing it. So I've opened a new one.

**Comment by mefuller** [comment]
ok, I'll work on this since we also have an issue being reported with the `classic` theme not compiling and this all started with a `classic`-only bug
Thanks for pointing out the drawbacks of `detokenize` @komascript  - I didn't realize it would break things as you describe
