### ISSUE TITLE
Communication platform for development

### ISSUE THREAD

**Issue by stephanlachnit** [moderncv/moderncv#91]
As discussed in https://github.com/moderncv/moderncv/pull/88, there was the idea to add an additional communication platform besides GitHub. One suggestion was to use a matrix.org channel.

This issue is for discussing this idea.

**Comment by ShadowMitia** [comment]
I don't mind which platform we use, matrix sounds fine (but I've never used it).

I think having a communication platform would help the team share ideas and resources. 

But my main point wouls be to help users and people who want to contribute to be able to ask questions and get help.
I've seen this happen on other projects, where people ask if their idea is good for the project, or if there is any interest in it. Maybe it's to get started. But once they get the feedback they usually contribute in the end but I'm pretty sure they  would never have done it if they couldn't come and ask.

**Comment by stephanlachnit** [comment]
> But my main point wouls be to help users and people who want to contribute to be able to ask questions and get help.
> I've seen this happen on other projects, where people ask if their idea is good for the project, or if there is any interest in it. Maybe it's to get started. But once they get the feedback they usually contribute in the end but I'm pretty sure they would never have done it if they couldn't come and ask.

Right, that sounds like a pretty good argument for me as well.

> I don't mind which platform we use, matrix sounds fine (but I've never used it).

Since @mefuller also prefers matrix, let's go with that one. I will create a channel and share the invite link.
