### ISSUE TITLE
Publications using multibib is not compatible with natbib

### ISSUE THREAD

**Issue by alanlivio** [moderncv/moderncv#94]
When using both `natbib` and `multibib`, the \bibliography does not appear as a subsection. 
More precisely, the following code from  `moderncv.cls` not work when using natbib.
```
\newcommand*{\bibliographyhead}[1]{\section{#1}}
 \AtEndPreamble{\@ifpackageloaded{multibib}{\renewcommand*{\bibliographyhead}[1]{\subsection{#1}}}{}}
```

I found this workaround:
```  
\renewcommand{\bibsection}{\subsection{\bibname}}
```

**Comment by mefuller** [comment]
@alanlivio can you provide some additional information on the error and work-around including a minimum working example?
Then I can look at this and see about integrating the fix.
Thanks
