### ISSUE TITLE
Add google scholar icon

### ISSUE THREAD

**Issue by alanlivio** [moderncv/moderncv#95]
Similar as twitter or github icon/link, should be interest modercv support a Google Scholar icon/link.
As example:
```
\social[scholar]{1bEOmkUAAAAJ}
```
In such examples, it produces following icon and link:
![](https://icon2.cleanpng.com/20180413/jie/kisspng-computer-science-google-scholar-doctor-of-philosop-google-5ad094511a4771.2300740815236188971077.jpg)
http://scholar.google.com.br/citations?user=1bEOmkUAAAAJ

**Comment by ShadowMitia** [comment]
We already have support for Google Scholar, you have to use `googlescholar`: `\social[googlescholar]{googlescholarid}`

**Comment by alanlivio** [comment]
Thanks, @ShadowMitia. It worked for me.
